spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://43.138.151.92:3306/user-center
    username: zita
    password: yupi666
    hikari:
      max-lifetime: 60000
  session:
    timeout: 86400
